// <auto-generated />
using System;
using LastResume.Data.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LastResume.Data.Migrations
{
    [DbContext(typeof(BlogCardContext))]
    [Migration("20231002232343_addTable2")]
    partial class addTable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LastResume.Entity.Models.BlogCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BlogCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("BlogKeyWords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogLongDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("BlogCards");
                });

            modelBuilder.Entity("LastResume.Entity.Models.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("LastResume.Entity.Models.BlogCard", b =>
                {
                    b.HasOne("LastResume.Entity.Models.BlogCategory", "BlogCategory")
                        .WithMany("BlogCards")
                        .HasForeignKey("BlogCategoryId");

                    b.Navigation("BlogCategory");
                });

            modelBuilder.Entity("LastResume.Entity.Models.BlogCategory", b =>
                {
                    b.Navigation("BlogCards");
                });
#pragma warning restore 612, 618
        }
    }
}
